//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FF6Hack.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FF6Hack.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Script generated by: Final Fantasy 3us Multi Editor, Coded by Lord J]
        ///[FF3usME version: 6.8.0]
        ///[File version: 1.00]
        ///[Section: Town Dialog]
        ///
        ///[caption #0]
        ///Biggs: There&apos;s the city_&lt;D24&gt;&lt;EOP&gt;
        ///Wedge: Hard to believe an Esper&apos;s been found intact there, a thousand years after the War of the Magi_&lt;D24&gt;
        ///
        ///[caption #1]
        ///Biggs: Think it&apos;s still alive?
        ///Wedge: Probably_
        ///_judging from the urgency of our orders. &lt;D24&gt;&lt;EOP&gt;
        ///Plus, they had us bring this sorceress with us.&lt;D24&gt;
        ///
        ///[caption #2]
        ///Biggs: Yeah_our wi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dialog_script {
            get {
                return ResourceManager.GetString("dialog_script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to | |TERRA|LOCKE|CYAN|SHADOW|EDGAR|SABIN|CELES|STRAGO|RELM|SETZER|MOG|GAU|GOGO|UMARO|
        ///&lt;D&gt;|||||^||&lt;centerEnd&gt;||&lt;N&gt;|&lt;I&gt;|&lt;S&gt;|||||A|B|C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|
        ///W|X|Y|Z|a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z|0|1|2|3|4|5|6|7|8|9|!|?|
        ///|:|&quot;|&apos;|-|.|,|...|;|#|+|(|)|%|~||@|&lt;note&gt;|=|&quot;|74|75|&lt;pearl&gt;|&lt;death&gt;|&lt;lit&gt;|&lt;wind&gt;|
        ///&lt;earth&gt;|&lt;ice&gt;|&lt;fire&gt;|&lt;water&gt;|&lt;poison&gt;| |e | t|: |th|t |he|s |er| a|re|in|ou|d | w|
        ///s|an|o | h| o|r |n |at|to| i|, |ve|ng|ha| m|Th|st|on|yo| b|me|y |en|it|ar|ll|ea|I |
        ///ed|  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dialog_table {
            get {
                return ResourceManager.GetString("dialog_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ff6 {
            get {
                object obj = ResourceManager.GetObject("ff6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Fantasy VI: Lore Complete v0.1
        ///          By Zachary White          
        ///====================================
        ///
        ///Base Patch: 
        /// - Final Fantasy VI: Woolsey Uncensored Edition v1.96 (Rodimus Primal)
        ///
        ///Tools Used:
        /// - FF6Hack v0.1 (Zachary White: http://www.primitiveconcept.com)
        /// - SnesEditing v0.1 (Zachary White: http://www.primitiveconcept.com)
        /// - FF3usMe v6.80 (Lord J: http://www.angelfire.com/pq/jumparound)
        /// - Zone Doctor CE v0.2.2 (madsiur: http://madsiur.net)
        /// - Lunar IPS v1.02 (FuSoYa: http://f [rest of string was truncated]&quot;;.
        /// </summary>
        public static string readme {
            get {
                return ResourceManager.GetString("readme", resourceCulture);
            }
        }
    }
}
